# Gin is the web framework
gin:
  # Possible values: "debug", "release"
  mode: release
  # App running behind a reverse proxy?
  # If set, HTTP Forwarded headers will be respected
  reverse_proxy: false

# The market watcher
market:
  auth: # YOUR_API_KEY
  enabled: true
  quote_update_time: 20m
  rate_update_time: 20m
  dex:
    quote_update_time: 5m
    api: https://dex.binance.org/api
  cmc:
    api: https://pro-api.coinmarketcap.com
    webapi: https://web-api.coinmarketcap.com
    widgetapi: https://widgets.coinmarketcap.com
    api_key: # YOUR_API_KEY
    map_url: https://raw.githubusercontent.com/trustwallet/assets/master/pricing/coinmarketcap
  fixer:
    rate_update_time: 1h
    api: https://data.fixer.io/api
    api_key: # YOUR_API_KEY
  compound:
    api: https://api.compound.finance/api
  coingecko:
    api: https://api.coingecko.com/api

storage:
  redis: redis://localhost:6379