apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "watchmarket.name" . }}
    chart: {{ template "watchmarket.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  MARKETS_COINMARKETCAP_KEY: {{ "" | b64enc }}
  MARKETS_FIXER_KEY: {{ "" | b64enc }}
  STORAGE_POSTGRES_URI: {{ "postgresql://user:pass@postgres/my_db?sslmode=disable" | b64enc }}
  STORAGE_REDIS: {{ "redis://redis:6379" | b64enc }}