apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rates
  namespace: {{ .Release.Namespace }}
  labels:
    app: api-rates
    chart: {{ template "watchmarket.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: api-rates
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        name: api-rates
    spec:
      containers:
      - env:
        - name: ELASTIC_APM_SERVICE_NAME
          value: watchmarket-api-helm
        - name: REST_API_APIS
          value: base,rates
        envFrom:
        - secretRef:
            name: secrets
            optional: false
        - configMapRef:
            name: config
            optional: false
        - secretRef:
            name: elastic
            optional: false
        image: "{{ .Values.image.repository }}:{{ .Values.image.apiTag }}"
        imagePullPolicy: IfNotPresent
        name: api-rates
        ports:
        - containerPort: 8421
          name: http
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - envFrom:
        - secretRef:
            name: secrets
        image: "{{ .Values.image.repository }}:{{ .Values.image.pgCheckTag }}"
        imagePullPolicy: IfNotPresent
        name: postgres-check
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
